import '../styles/globals.css';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Spotify 2.0</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="https://pnggrid.com/wp-content/uploads/2021/05/Spotify-PNG-Logo-768x767.png"
                />
            </Head>
            <Component {...pageProps} />
        </>
    );
}

export default MyApp;
