import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
      <div>
          <Head>
              <title>Spotify 2.0</title>
              <meta name="description" content="Generated by create next app" />
              <link
                  rel="icon"
                  href="https://pnggrid.com/wp-content/uploads/2021/05/Spotify-PNG-Logo-768x767.png"
              />
          </Head>

          <main>
              {/*Sidebar */}
              {/*Center*/}
          </main>
          <div>{/* Player */}</div>
      </div>
  );
}
